config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'admin'
      can :manage, Post
      can :manage, Like
      can :manage, Comment
    else
      can %i[create read update], Post
      can :destroy, Post, author_id: user.id
      can %i[create read update], Comment
      can :destroy, Comment, author_id: user.id
    end

    return unless user.persisted?

    can :create, Like
  end
end

app/models/application_record.rb
# Base class for all application models.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_comments_counter_for_a_post
  after_destroy :update_comments_counter_for_a_post

  private

  def update_comments_counter_for_a_post
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter_for_a_post

  private

  def update_likes_counter_for_a_post
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }

  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_author_posts_count
  after_destroy :update_author_posts_count

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_author_posts_count
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  def new
    comment = Comment.new
    respond_to do |format|
      format.html { render partial: 'shared/new_comment_form', locals: { comment: } }
    end
  end

  def create
    comment = Comment.new(comment_params)
    comment.post = Post.find(params[:post_id])
    comment.author = current_user

    respond_to do |format|
      format.html do
        if comment.save
          redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id]),
                      notice: 'Comment was successfully created.'
        else
          render :new
        end
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = Post.find(@comment.post_id)
    @comment.destroy
    redirect_to user_post_path(user_id: post.author_id, id: post.id), notice: 'Comment was successfully deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new
    like.post = Post.find(params[:post_id])
    like.author = User.find(params[:user_id])

    if like.save
      flash[:success] = 'Like saved successfully'
    else
      flash.now[:error] = 'Error: Like could not be saved'
    end
    redirect_to "/users/#{current_user.id}/posts/#{like.post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find_by(id: params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def new
    post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: } }
    end
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.find(params[:id])
    @currrent = current_user
    @like = Like.new
  end

  def create
    post = current_user.posts.new(post_params)

    respond_to do |format|
      format.html do
        if post.save
          redirect_to user_posts_url(user_id: current_user.id), notice: 'Post was successfully created.'
        else
          render :new
        end
      end
    end
  end

  def destroy
    puts 'hello'
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.author_id), notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# Module to provide helper methods for the application views.
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-color-backgroung text-color-text">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<!-- app/views/posts/index.html.erb -->

<div>
  <%= render partial: 'shared/user_show', locals: {user: @user} %>

  <% @posts.each do |post| %>
    <%= render partial: 'shared/post', locals: {post: post} %>
    <%= render partial: 'shared/comment', locals: {post: post} %>
  <% end %>

  <button class="mx-auto font-bold w-5/12 md:w-1/10 mb-5 border-solid border-4 border-gray-500">Pagination</button>

</div>

app/views/posts/new.html.erb
 <h1>New Post</h1>
  
<%= form_with model: post, url: user_posts_path, method: :post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  
  <button>
    <%= form.submit 'Create Post' %>
  </button>
<% end %>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->
<div class="flex-col">
  <div id="post" class="border-solid border-4 border-black md:w-1/2 mx-auto w-full mb-5">
    <div class="flex justify-between">
      <div>
        <h2 class="font-bold ml-3"><%= @post.title %><span class="font-normal"> by <%= @user.name %></span></h2>
      </div>

      <div class="mr-5">
        <p>Comments: <span class="font-bold"><%= @post.comments_counter%>, </span>Likes: <span class="font-bold"><%= @post.likes_counter %></span></p>
      </div>
    </div>

    <div>
      <p class="mt-5 ml-3" ><%= @post.text %></p>
    </div>

    <div class="flex justify-between">
      <div class="mb-5 mt-5 ml-3 flex gap-5">
        <%= render partial: 'shared/add_like' %>

        <a href="/users/<%= @user.id %>/posts/<%= @post.id %>/comments/new" class="border-4 border-black"> New comment</a>
      </div>

      <% if can? :destroy, @post %>
      <div class="mb-5 mt-5 border-4 border-black mr-5">
        <%=  link_to 'Delete', user_post_path(@current_user.id, @post.id), class: "cursor:pointer", data: { "turbo-method": :delete } %>
      </div>
      <% end %>

    </div>

  </div>

  <%= render partial: 'shared/comment', locals: {post: @post} %>
</div>

app/views/shared/_add_like.html.erb
<% if can? :create, @like %>
  <a class="border-4 border-black cursor-pointer">
      <%= form_with url: "/users/#{@current_user.id}/posts/#{@post.id}/likes", model: @like do |form| %>
        <%= form.submit 'Like', class: 'px-4 py-2 border-2 border-black cursor:pointer' %>
      <% end %>
  </a>
<% end %>

app/views/shared/_comment.html.erb
<div class="border-4 border-black md:w-1/2 mx-auto w-full mb-5">
  <% Comment.includes(:author).where(post_id: post.id).each do |comment| %>
    <div class="flex gap-5 mt-4">
      <div><%= comment.author.name %>:</div>
      <div class="w-3/4 relative">
        <%= comment.text %>
        <%= link_to 'Delete', user_post_comment_path(@current_user.id, post.id, comment.id), class: "border-4 border-black block w-[80px] right-[20px]", data: { "turbo-method": :delete } if can? :destroy, comment %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_new_comment_form.html.erb
<h1>New Comment</h1>
  
<%= form_with model: comment, url: user_post_comments_path, method: :post do |form| %>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<a id="<%= post.id %>" href="<%= user_path(@user.id) %>/posts/<%= post.id %>" class="border-solid border-4 border-black md:w-1/2 mx-auto w-full mt-5 block hover:border-red-600">
  <h2 class="font-bold ml-3"><%= post.title %></h2>
  <p class="mt-5 ml-3" ><%= post.text %></p>
  <p class="mt-5 right-2 ml-3 mb-5">Comments: <span class="font-bold"><%= post.comments_counter%>, </span>Likes: <span class="font-bold"><%= post.likes_counter %></span></p>
</a>

app/views/shared/_user.html.erb
<!-- app/views/users/shared/_user.html.erb -->

<a href="<%= user_path(user.id) %>" id="<%= user.id %>" class="flex justify-between items-center w-full md:w-1/2 mx-auto mb-5 border-gray-200 rounded-lg shadow h-full hover:bg-gray-100 hover:border-color-red hover:border-2">
  
  <div class="w-1/4 rounded-lg shadow">
    <img src="<%= user.photo %>" alt="User Photo">
  </div>

  <div class="w-2/3 relative h-full bg-color-red text-color-backgroung rounded-lg">
    <h1 class="md:text-4xl font-extrabold text-xl absolute md:top-11 md:left-11 top-2 ml-3"><%= user.name %></h1>
    <div class="absolute right-4 bottom-4">Total posts: <span class="font-extrabold"><%=user.posts_counter %></span></div>
  </div>

</a>

app/views/shared/_user_show.html.erb
<!-- app/views/users/shared/_user_show.html.erb -->
<!-- user partial used for User#show and post#index -->

<div id="<%= user.id %>" class="flex justify-between items-center w-full md:w-1/2 mx-auto bg-white border-gray-200 rounded-lg shadow">
  
  <div class="w-1/4 rounded-lg shadow">
    <img src="<%= user.photo %>" alt="User Photo">
  </div>

  <div class="w-2/3 h-full">
    <h1 class="md:text-4xl font-extrabold text-xl"><%= user.name %></h1>
    <div>Total posts: <span class="font-extrabold"><%=user.posts_counter %></span></div>
  </div>

</div>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<div class="flex flex-col w-full gap-y-5">
  <% @users.each do |user| %>
    <%= render partial: 'shared/user', locals: {user: user} %>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<div class="flex flex-col w-full">
  <div id="userInfos" class=" bg-white border-gray-200 rounded-lg shadow mt-1 md:w-1/2 mx-auto mb-5 pl-5 pt-2 pb-2>
        <%= render partial: 'shared/user_show', locals: {user: @user} %>

        <div id="bio" class="border-4 border-black mt-4 md:w-1/2 mx-auto mb-5">
          <h2 class="font-extrabold text-xl">Bio</h2>
          <p><%= @user.bio %></p>
        </div>
  </div>

  <% @user.posts.each do |post| %>
    <%= render partial: 'shared/post', locals: {post: post} %>
  <% end %>

  <a id="view-all-posts" href="<%= @user.id %>/posts" class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 shadow-lg shadow-red-500/50 dark:shadow-lg font-medium rounded-lg text-sm px-5 py-2.5 text-center mx-auto md:w-1/5 w-1/2">See all posts</a>

</div>